### ISSUE TITLE
Unable to save remote sensor names

### ISSUE THREAD

**Issue by Kraftwerx** [KurtSanders/STAmbientWeather#11]
When setting up the smart app on a Note 8, there is no option to save the remote sensor names.  The only thing you can do is go back which clears all info and you have to start over.

**Comment by Kraftwerx** [comment]
I kept banging around and found that I had to set the SMS notifications.  Now I am unable to turn that off per the instructions to leave the field blank.

**Comment by KurtSanders** [comment]
Dear Kraftwerx,

I apologize for this issue you encountered and have release a new version that you can update to and remove your mobile number.

# Ambient Weather Station

## **V4.23** 

#### Bug Fix:
1. Corrected a condition where a user, who had activated Weather Alerts/Notifications, could not deactivate the Weather Alerts/Notifications by removing the mobile phone number as directed in the input field's instructions.  Removing the mobile phone from the input field is now possible and will defeat Weather Alerts/Notifications.
2. Changed default Weather Alert/Notifications interval to every 4 hours.

  ### ST GitHub Settings for 4.23
| Name | Value |
|------|-------|
|Owner | kurtsanders |
|Name: | STAmbientWeather|
|Branch| **master**|

**Required Files since previous version MUST be installed and published to your SmartThings IDE Repositories**  _(Use ':arrow_down:Update from Repo')_

| IDE Repository    | Filename | Status |
| :---: | :----------| :---:  |
| My SmartApps      | kurtsanders : Ambient Weather Station | **Updated** |
| My Device Handler | kurtsanders : Ambient Particulate Monitor | **UnChanged** |
| My Device Handler | kurtsanders : Ambient Weather Station | **UnChanged** |
| My Device Handler | kurtsanders : SmartWeather Tile Station | **UnChanged** |
| My Device Handler | kurtsanders : Ambient Weather Station Remote Sensor | **UnChanged** |

Required: Please run Ambient Weather Station SmartThings SmartApp setup after installing these updated files.

**Comment by KurtSanders** [comment]
I will need to check this out this issue on my old Android device.  I am mainly an iOS developer and SmartThings on Android has issues that the iOS client does not experience.  Makes me crazy!

> When setting up the smart app on a Note 8, there is no option to save the remote sensor names. The only thing you can do is go back which clears all info and you have to start over.
