### ISSUE TITLE
Issue with a ST setup on the ST app tiles

### ISSUE THREAD

**Issue by rschulingkamp** [KurtSanders/STAmbientWeather#17]
Kurt,
I set up my Ambient weather WS-50 to Smartthings.  When I look at the tiles on the ST app, my remote sensors only display the humidity.   When I touch a tile and open up that sensor both temp and humidity are present, but the units for temp is "C", even though I'm using F and the numerical value is the F number, but with a oC after.
Bob

**Comment by KurtSanders** [comment]
Sorry to hear you are having problems Bob, perhaps we can solve it. 

What mobile device and SmartThings mobile client (New/Old) are you using:
1. Apple iOS (preferred) or Android mobile device
2. Legacy ST client (preferred) or New ST mobile client

Can you verify that you have the following preferences/options set in the Ambient Weather SmartApp: 
1.  Selected '˚F' in the 'Select Weather Units of Measure' along with other defaults

I might need temporary access to your Ambient API weather string to install on my ST and see, test & debug what you are seeing.  If so, we can trade emails and you can send the API confidentially.

**Comment by rschulingkamp** [comment]
Kurt,
I sent an email to you just now to be sure I got it right.
Thanks
Bob

**Comment by KurtSanders** [comment]
I received it!

**Comment by KurtSanders** [comment]
Application installed with end users API key and screen shots of the tiles have been mailed to end user.

**Comment by KurtSanders** [comment]
This has been fixed in the latest 5.03 release in github

**Comment by rschulingkamp** [comment]
Hey Kurt,

I’m so glad to see that you worked on this.  I believe I did the update correctly, although I sometimes am missing one of my sensors, but they’re all there now.  The only question I have is around the tiles that are loaded on the home page.  They display only the humidity not the temperature.  Even when a sensor doesn’t have a humidity probe it reports “0.0%” on the tile.

Did I do something wrong in the update?

Thanks

Bob

**Comment by KurtSanders** [comment]
I am not sure what is occurring in your WS-50 Ambient weather system setup, there are so many models and configurations that one can have. Most remote sensor devices have at least a temperature value and optionally humidly.  If you are seeing something different which I suspect you are, I will need your Ambient API key for short term testing on my ST system and to debug any program logic issues.  I think you shared the API key before, but I have since deleted it, so if you can resend via email (kurt at kurtsanders dot com) that would help in solving this issue.

The remote sensor ST Tile has both temperature and humidly placeholders, so if a remote weather sensor only reports temperature, the humidity value will be either 0 or N/A..  That is because ST mobile client does not allow device tiles to have dynamic configurations placeholders, they are static at compile time.  I will only be able to test with the ST Legacy mobile client since I have not upgraded to the new client.

Again, I can see perhaps what you are seeing when I obtain your API for limited local testing
