### ISSUE TITLE
Temperature Units Off

### ISSUE THREAD

**Issue by justinrsteele** [KurtSanders/STAmbientWeather#18]
Hi Kurt, I've been using your Ambient Weather station code for the last few days, and it's been so helpful. Thank you for creating it! I am bumping into one issue I wanted to flag. I'm using the New ST mobile app on an Android mobile device (Pixel 4). While I have selected Fahrenheit for my temperature unit and my weather station tile and individual sensors all show the numerical values in degrees Fahrenheit, most of them show "C" instead of "F" as the label. For example, my weather station is currently reading "78.6 C." I wasn't too worried about it since the numerical value is correct, but today I tried to create an automation that used the weather station temperature as a trigger, and it is only allowing me to enter values between -20 and 50. That seems to be bounded by Celsius, not a Fahrenheit scale. I thought about changing everything to Celsius to get the trigger right, but then it would mess up my link to ActionTiles where I'm showing my sensors (preferably in Fahrenheit). Any thoughts? I have tried installing the Old ST app and adding my weather station there, but no luck (same issue). I also tried reestablishing the preferences, but no luck there either.

**Comment by KurtSanders** [comment]
Dear Justin,

I have not personally migrated to the new ST mobile client  I have been hearing that many custom developed apps and this app have some display issues with the temperature units and dashboard issues. 

I have been hesitant to load my numerous home automations into the new ST mobile app for fear that something will not migrate as expected and then I am in trouble with all my automations that are working perfectly in the legacy ST App.  I am very disappointed that ST engineers have touted that the new ST mobile client is very 'compatible' with end user developed apps, but this is simply not true as you have found out.  I will try to look over the documentation for the new ST client to see what I might be able to correct/add in Ambient Weather Station to get the units to match the intended preferences, but no promises.  I do not want to have to create two apps at this point.,

So before I decide to migrate my home and the numerous custom apps I have created over the years to the new ST mobile client, can you try to load the legacy ST mobile app on your phone, install/setup Ambient Weather Station and  WebCore if they are not shown where you can setup and execute the weather automations for your home. I know this isn't ideal, but it is all I can offer at this point because Ambient Weather Station isn't 100% compatible with the new ST Ambient Weather Station.

**Comment by KurtSanders** [comment]
Dear Justin,

Before I try to change a few items in the code that might make the units display as F in the new ST mobile client, would you check to see if you can use the variable **tempf_real** which is formatted as numeric without a units designation.  The _real variables are posted to allow ST users access to the raw data.  Let me know if this variable works for an automation.

**Comment by justinrsteele** [comment]
Hi Kurt, thanks so much for your replies. I've tried to install WebCore a
couple of times, but I can't get it to show up in my SmartApps. I think
maybe because I joined the SmartThings ecosystem in 2019 and went straight
to the new app because I didn't know any better, it's making it difficult
for me to do things in the legacy app. I do have the legacy app installed
on my phone, but the WebCore smart app doesn't show up there either (I've
tripled checked that have everything set in SmartThings IDE per the wiki
installation instructions). Since I can't get WebCore to load, I don't
believe I can access the _real variables, right? I'm stuck with the new app
and their native Automations function. In the new app, you can add "If"
conditions for specific devices, and when I select the SmartWeather tile
there, that's when I see that the temperature range input value is limited
to -20 to 50.

Totally understand if this is something you're not able to address given
that you're not currently using the new app. Really appreciate you looking
at it though!

**Comment by justinrsteele** [comment]
Hi Kurt, quick update. Good news, I was able to get it working! I
uninstalled all my SmartApps and reinstalled STAmbientWeather and WebCore.
After I did that, the ST app allowed me to install WebCore. Once I got
WebCore up and running, I was able to create a Piston that successfully
compared the temperature of my weather station to a sensor in my bedroom
and then triggered a window fan. I saw the *tempf_real* variable, but I
tried the Temperature value first, and Temperature worked just fine. The
native automation function in the ST app (the new one) still does not allow
me to enter a temperature value above 50, but as you said, the new ST app
is full of shortcomings, so I'm just going to go around it and use WebCore.
So I'm all set for now. Thank you again!

**Comment by KurtSanders** [comment]
Dear Justin,

I have modified Ambient Weather Station SmartApp to 5.03 today that has some units of measure changes that might work better in the new ST Mobile Client for displaying and using temperature values in automations.  Please use the **Update from Repo** in the ST IDE for this SmartApp to see if this change helps you with temperature automation events...

**Comment by justinrsteele** [comment]
Hi Kurt, that update did indeed fix the problem with the new ST Mobile
Client. I am now able to enter temperature values from -4 to 122 in the
automations. The temperature units also all read in Fahrenheit and display
"F" rather than "C." Thanks for the update!

**Comment by KurtSanders** [comment]
Glad that 503 update worked for you (and others).  I will post this on the forum for others.

I will migrate to the new ST mobile client someday, or when I feel that the benefits outweigh the {perceived} negatives.  I have so many legacy "tweaks" that the thought of re-developing them for the new platform is more than I wish to tackle for now.  

Good luck moving forward with the home automations!
