### ISSUE TITLE
unable to add device

### ISSUE THREAD

**Issue by hgodwin5** [KurtSanders/STAmbientWeather#20]
hello, i recently updated to the new version. upon update none of my devices were populating and after uninstalling/reinstalling i can't get past the select station page.

Android
Legacy ST client

**Comment by KurtSanders** [comment]
Dear hgodwin5,

I am sorry to hear this trouble.  

I would try a fresh re-install after removing the Ambient Weather Station which should delete all the created child devices.  Then from the ST IDE, remove the Ambient Weather Station SmartAPP and all Ambient Weather Devices and DTH's.   Making sure that there isn't anything left from this app and DTH's, then install the Ambient Weather Station SmartApp and DTH's from 'Update from REPO'.

This app works for sure on iOS mobile devices, so I'm hoping it isn't a Android mobile client issue.  I can try to install with your Ambient Weather Station using your API if the fresh install fails.

**Comment by hgodwin5** [comment]
Thanks a ton for your help. I tried the uninstall/reinstall no success. I had it working like a champ prior to my version update, I was really behind and jumped from 4.3 to 5.x. I noticed that when I go to select the unit it has a null value at the end (2740null), and when running through the smart things simulator it looks like it is generating a null error. 

7c83f406-1dcf-437d-9368-2bc2f687d00a 12:04:06 AM: error java.lang.NullPointerException: Cannot get property 'location' on null object @line 149 (doCall)

**Comment by KurtSanders** [comment]
Dear hgodwin5,

The error in the Ambient Weather Station is generated due to the missing 'location' information for your Ambient Weather Station.  Would you mind adding a location to your weather station at https://ambientweather.net/devices. This is a required field that Ambient Weather Station should mandate, but they don't and it causes a null value in the data. 

![image](https://user-images.githubusercontent.com/12133562/83735814-d5895b80-a61e-11ea-9319-c5d503375495.png)

**Comment by hgodwin5** [comment]
Fixed and everything is working! Thanks for the help trouble shooting!
