### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by agfree** [KurtSanders/STAmbientWeather#25]
Using Hubitat Package Manager, all is well until the final phase of installation.  Any insight here?

```
app:972020-12-18 10:43:37.705 errorgroovy.lang.MissingMethodException: No signature of method: user_app_kurtsanders_Ambient_Weather_Station_108.input() is applicable for argument types: (java.util.LinkedHashMap, org.codehaus.groovy.runtime.GStringImpl) values: [[type:text, title:Ambient Particulate Monitor PM25, defaultValue:PM25, ...], ...]
Possible solutions: inspect(), wait(), run(), run(), find(), any() on line 370 (remoteSensorPage)
app:972020-12-18 10:43:34.924 infoAmbient Weather Station: Mac: A4:CF:12:B4:ED:90, Name/Loc: North Third/La Conner
app:972020-12-18 10:43:28.776 infoAmbient Weather Station: Mac: A4:CF:12:B4:ED:90, Name/Loc: North Third/La Conner
app:972020-12-18 10:42:36.211 infoSUCCESS: AmbientStationData successfully updated for runID: 0
app:972020-12-18 10:42:35.994 infoAmbientStationData Time difference is 10 secs between last execution
app:972020-12-18 10:42:35.992 infoStart: AmbientStationData runID: 0 at 10:42:35 AM
app:972020-12-18 10:42:35.945 infoWaiting 10 seconds to Try HttpGet Again runID 0: Attempt #1
app:972020-12-18 10:42:35.930 debugAmbient Weather Station API Data runID 0: java.net.SocketTimeoutException: Read timed out
app:972020-12-18 10:42:25.725 infoAmbientStationData Time difference is 0 secs between last execution
app:972020-12-18 10:42:25.723 infoStart: AmbientStationData runID: 0 at 10:42:25 AM
```

**Comment by KurtSanders** [comment]
I am away for the Holidays and I will resume limited support beginning in 2021.   PM25 devices seem to be problematic for the HE port of Ambient Weather and I will see if I can get to bottom of this when I re-write this ST app to be more native to HE.

My quick thoughts are check to insure that the [Ambient Particulate Monitor DTH](https://raw.githubusercontent.com/KurtSanders/STAmbientWeather/master/hubitat/devicetypes/kurtsanders/ambient-particulate-monitor.src/ambient-particulate-monitor.groovy) is installed as a device?

**Comment by agfree** [comment]
> My quick thoughts are check to insure that the [Ambient Particulate Monitor DTH](https://raw.githubusercontent.com/KurtSanders/STAmbientWeather/master/hubitat/devicetypes/kurtsanders/ambient-particulate-monitor.src/ambient-particulate-monitor.groovy) is installed as a device?

I see "Ambient Particulate Monitor" in drivers code, but no device is present because it errors out before installation is complete, if that makes sense.

**Comment by KurtSanders** [comment]
That Ambient Weather Station driver and the two drivers will be automatically downloaded and installed when AWS is installed via Hubitat Package Manager (HPM).  Here is a link to the [HPM json repository](https://github.com/KurtSanders/STAmbientWeather/blob/master/hubitat/packageManifest.json) that has the AWS drivers that are required to be installed via HPM.

**Comment by agfree** [comment]
I see all three drivers appear when installing via HPM. The error remains.

**Comment by KurtSanders** [comment]
Sorry, I'm ready to investigate....   Yea 2021...   

Would you mind sending your Ambient API key string via email so that I can debug your situation, as I do not have the same configuration and cannot reproduce what you are seeing.  Please send to kurt at kurtsanders dot com if you agree.  I will delete the string after testing.

**Comment by KurtSanders** [comment]
Dear Alex,

I have updated Ambient Weather Station (AWS) in the Hubitat Package Manager to reflect a new version 5.0.4 that addresses the 'missing PM25 device' issues you found with a PM25 weather sensor.  

Because you are missing the HE PM25 device in the HE devices list, which usually is installed during the initial AWS setup, you will need to remove and reinstall the AWS again.  Here are the steps I recommend:

Remove the AWS app from HE (you do not need to delete the device and application files as they will be updated in step 2)
Upgrade to AWS 5.0.4 through Hubitat Package Manager 'Update" option
Reinstall AWS through the HE 'Add User App' and complete the preference choices. 

Let me know if this works for you as it did for me using your AWS API string.

**Comment by agfree** [comment]
Success!  It installed without a hitch.  Thanks!

**Comment by KurtSanders** [comment]
Glad to hear and thanks for hanging in there during the holidays!
