### ISSUE TITLE
Multiple Ambient weather station units app force chooses the first unit

### ISSUE THREAD

**Issue by spartan77777** [KurtSanders/STAmbientWeather#6]
I have 3 separate Ambient weather units in multiple locations.  When I generate the API key I have no control over which one I am generating for which I assume it generates for the overall account.  Upon passing the API into the smart app it grabs the first unit on the account without giving me any option to choose which one I am looking to connect to through the smart app.  Otherwise I get the data from the first unit correctly.

**Comment by KurtSanders** [comment]
You are correct.   You are the first with multiple stations and all of my Ambient/SmartThings users have ONE weather station with multiple remote sensors, and as a result,  the App only picks up the first weather station as the ONLY station and disregards all other data sent.  

I will need to code to expect N number of weather stations.  Since I do not have multiple weather stations, I would need _temporary access_ to your Ambient API key to start the STAbientWeather development change.  If you are OK with that proposal as I have done with others with unique configurations, I will send you a PM to spartan77777 via the [Community forum at SmartThings](http://community.smartthings.com/) .  That way this key and message can be private.

**Comment by spartan77777** [comment]
I am perfectly OK with sharing my API with you to support the enhancement.  Looking forward for the PM.
Thanks.

**Comment by KurtSanders** [comment]
Already sent the PM to **spartan77777**.   This is your username on the community SmartThings forum, right?

https://community.smartthings.com/u/spartan77777/messages

**Comment by KurtSanders** [comment]
V4 allows for multiple instances of Ambient Weather Station to accomodate an API that reports more than one weather station.
